- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost
  vars:
    COURSE: DevOps with Aws
    DURATION: 10HRS
    Trainer: sivakumar reddy
  tasks:
  - name: print the course info
    vars:
    
    ansible.builtin.debug:
      msg: "course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer}}"